application: power-suite
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /app/css
  static_dir: app/css
  mime_type: text/css

- url: /app/js
  static_dir: app/js
  mime_type: text/javascript

- url: /app/components
  static_dir: app/components
#  mime_type: text/javascript

- url: /app/bower_components
  static_dir: app/bower_components
#  mime_type: text/javascript

- url: /app/partials
  static_dir: app/partials
  mime_type: text/html

- url: (.*)/.*
  static_files: app/index.html
  upload: app
#
#- url: (.*)
#  static_files: app
#  upload: app









