application: sturdy-tuner-92307
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /js
  static_files: app/js
  upload: /js
  mime_type: text/javascript; charset=utf-8

- url: /css
  static_files: static/css
  upload: /css
  mime_type: text/css; charset=utf-8

- url: /bower_components
  mime_type: text/javascript
  static_files: static/bower_components/
  upload: app/bower_components/.*?/.*

- url: (.*)/
  static_files: app/index.html
  upload: app

- url: (.*)
  static_files: app
  upload: app










